spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'
            allowedHeaders: '*'      
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
            
     # add microservice routes here
      routes:  
      
      - id: users
        uri: lb://users
        predicates:
        - Path=/auth/**,/users/**
        # No filters required
        
      - id: products
        uri: lb://products
        predicates:
        - Path=/products/**,/categories/**

                        
server: 
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost